### ISSUE TITLE
Zielgruppendefinition

### ISSUE THREAD

**Issue by lennybacon** [Opendatal/ODDWuppertal2015#1]
Für wen soll das Event attraktiv sein und warum?

Au dem Treffen habe ich mal vom Whiteboard abgeleitet/geschrieben:
- Programmierer
- Designer
- Dataisten (Jurnalisten/Methodiker/Wissenschaftler/Statistiker/...)
- Studenten/Profs
- Bürger

**Comment by SamZeini** [comment]
Mir fallen folgende Ansprechpartner ein, wenn es um Data Driven Journalismus geht:
https://twitter.com/RainerStriewski
http://ddjnrw.de/
