### ISSUE TITLE
Sponsoring

### ISSUE THREAD

**Issue by exmatrikulator** [Opendatal/ODDWuppertal2015#2]
Wofür wollen wir Geld haben?
Und wie viel?

**Comment by phneutral** [comment]
Ich habe einen Plakatentwurf gemacht und fände auch Flyer nicht verkehrt.
Raummiete und Catering ständen natürlich auch auf der Liste.

**Comment by exmatrikulator** [comment]
USV: Möchte wissen was zu wieviel
/dev/tal: Unterstützt! Will aber auch wissen, was zu wieviel

**Comment by lennybacon** [comment]
1. Wo ist denn das Plakat?
2. Flyer wofür? Sponsorship? Die Veranstaltung?
3. Mit USV meint Ihr bestimmt nicht http://de.wikipedia.org/wiki/Unterbrechungsfreie_Stromversorgung - aber was dann?

**Comment by exmatrikulator** [comment]
USV: UtopiaStadtVerein

**Comment by lennybacon** [comment]
@exmatrikulator Danke!

**Comment by phneutral** [comment]
Habe einen Screenshot mal ins Wiki gepackt.

**Comment by sn0wdiver** [comment]
Wo wir gerade dabei sind, wann wollen wir Plakate und Flyer bestellen?

**Comment by lennybacon** [comment]
Plakat gefällt mir!

**Comment by phneutral** [comment]
Meinetwegen möglichst bald :)
Würde mich drum kümmern, wenn alle einverstanden sind.
