### ISSUE TITLE
oddw.de aktualisieren

### ISSUE THREAD

**Issue by exmatrikulator** [Opendatal/ODDWuppertal2015#3]

**Comment by lennybacon** [comment]
Sollen wir dafür ein Repository anlegen?

**Comment by lennybacon** [comment]
Noch jemand mit dabei?

**Comment by phneutral** [comment]
oddw.de ist 2012 von Guido angelegt worden. Bis auf die Admin-Rechte für das dort installierte CMS haben wir auf die Domain leider keinen Zugriff. Das wird also eher schwierig :(

**Comment by phneutral** [comment]
Ich hab ihn mal zu opendatal hier auf github eingeladen (gallenkamp).
